FROM node:21-alpine AS builder

WORKDIR /usr/src/app
RUN apk add --no-cache tzdata && \
  ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
  echo $TZ > /etc/timezone

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install 
COPY . .


RUN apk add --no-cache openssl \
  && sh -c  npx wait-for-it.sh db:5432 --  sh -c "sleep 5 && pnpm migrate:up" \
  && sh -c  npx wait-for-it.sh db:5432 --  sh -c "sleep 5 && pnpm seed" \
  && pnpm prisma:generate 

EXPOSE 4000

CMD ["pnpm", "start:dev"]

