services:
  db:
    image: postgres:15.0
    restart: always
    container_name: db-inventory
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root.123
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    networks:
      - inventory-network
    volumes:
      - db-data:/var/lib/postgresql/data

  inventory-api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - NODE_ENV=development
      - TZ=America/El_Salvador
    ports:
      - '${PORT}:4000'
      - '9229:9229'
    networks:
      - inventory-network

volumes:
  db-data:

networks:
  inventory-network:
    driver: bridge
