services:
  db:
    image: postgres:15.0
    restart: always
    container_name: db-inventory
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root.123
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    networks:
      - inventory-network
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - NODE_ENV=production
      - TZ=America/El_Salvador
    ports:
      - "${PORT}:3000" 
    networks:
      - prueba-network


volumes:
  sqlserver-data:
    driver: local

networks:
  prueba-network:
    driver: bridge
