FROM node:21-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install 
COPY . .

RUN pnpm run prisma:generate

EXPOSE 4000
RUN apk add --no-cache openssl
CMD ["pnpm", "start:dev"]

